version: '2'
services:
  app:
    extends:
      file: docker-compose.base.yml
      service: app
    ports:
     - "${APP_PORT}:80"
  node:
    extends:
      file: docker-compose.base.yml
      service: node
  mysql_testing:
    extends:
        file: docker-compose.base.yml
        service: mysql
    ports:
     - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
  redis_testing:
    extends:
      file: docker-compose.base.yml
      service: redis
networks:
  baufragen:
    driver: "bridge"
volumes:
  baufragen_mysqldata:
    driver: "local"
  baufragen_redisdata:
    driver: "local"